(()=>{
'use strict';
const VERSION='12.0.0',CODE=12,ENDPOINT='./update.json',KEY='kifnet_web_v12_seen';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function style(){if(document.getElementById('k12Style'))return;const s=document.createElement('style');s.id='k12Style';s.textContent='.k12Release{position:fixed;left:14px;right:14px;bottom:18px;z-index:12000;display:flex;gap:12px;align-items:flex-start;padding:15px;border:1px solid var(--line);border-radius:24px;background:color-mix(in srgb,var(--card) 96%,transparent);backdrop-filter:blur(20px);box-shadow:0 22px 70px rgba(0,0,0,.18);animation:k12In .52s cubic-bezier(.16,1,.3,1)}.k12Release[hidden]{display:none}.k12Icon{width:44px;height:44px;flex:none;border-radius:15px;background:color-mix(in srgb,var(--p) 12%,var(--card));color:var(--p);display:grid;place-items:center;font-size:20px}.k12Body{min-width:0;flex:1}.k12Body>b{display:block;font-size:14px}.k12Body>p{margin:5px 0 8px;color:var(--muted);font-size:11px;line-height:1.9}.k12Body ul{margin:0 0 10px;padding-right:19px;color:var(--muted);font-size:11px;line-height:1.9}.k12Actions{display:flex;gap:7px}.k12Actions button{padding:8px 12px;border-radius:12px;background:var(--p);color:#fff;font-weight:700;font-size:11px}.k12Actions .secondary{background:var(--bg);color:var(--text)}@keyframes k12In{from{opacity:0;transform:translateY(24px) scale(.97)}to{opacity:1;transform:none}}@media(min-width:700px){.k12Release{left:50%;right:auto;width:min(590px,calc(100% - 28px));transform:translateX(-50%)}}';document.head.appendChild(s)}
function show(info){const code=Number(info?.versionCode)||0;if(!info||code<=CODE||localStorage.getItem(KEY)===String(code))return;const box=document.createElement('section');box.className='k12Release';box.innerHTML=`<div class="k12Icon">↗</div><div class="k12Body"><b>${esc(info.title||'نسخه جدید کیف‌نت')}</b><p>${esc(info.message||'نسخه جدید وب آماده است.')}</p>${Array.isArray(info.changes)?'<ul>'+info.changes.slice(0,7).map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>':''}<div class="k12Actions"><button data-go>بروزرسانی</button><button class="secondary" data-close>بعداً</button></div></div>`;document.body.appendChild(box);box.querySelector('[data-close]').onclick=()=>{localStorage.setItem(KEY,String(code));box.remove()};box.querySelector('[data-go]').onclick=()=>{localStorage.setItem(KEY,String(code));location.reload()}}
async function check(){try{const r=await fetch(ENDPOINT+'?t='+Date.now(),{cache:'no-store'});if(r.ok)show(await r.json())}catch(e){}}
style();setTimeout(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});check()},1800);window.addEventListener('online',check);document.addEventListener('visibilitychange',()=>{if(!document.hidden)check()});window.KifNetApp={version:VERSION,versionCode:CODE,checkForUpdate:check};
})();
